# .github/workflows/devguard.yml
name: DevGuard Workflow

on:
  push:
 
jobs:
  devguard-scanner:
    uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
    with:
        asset-name: "l3montree-cybersecurity/projects/devguard/assets/devguard-web"
    secrets:
        devguard-token: ${{ secrets.DEVGUARD_TOKEN }} 